title: Nadeem Ahmed
logo: https://github.com/nadeem-ahmed-git/Nadeem-s_Data_Analyst_Portfolio/assets/113108799/5f3b05b1-79ea-459a-9e98-940e80e6bdbe
description: Data Analyst
theme : jekyll-theme-architect
